### ISSUE TITLE
Linux Simulator bugs

### ISSUE THREAD

**Issue by delvingdeep** [Davidnet/kiwix#2]
#### There seems to be few bugs in Linux version(_tested on Ubuntu 16.04_) of simulator.
- Once brakes are applied it doesn't start in forward direction.
- Sometimes it keeps on running in reverse direction, irrespective of keyboard inputs
- Also the crash meter is continuously running, despite of smooth robot movement

**Comment by Davidnet** [comment]
Corrected in a new release.
